"""PDF export API route."""

import io
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.api.deps import get_database_session, get_authenticated_user
from app.models.chat_history import ChatHistory

router = APIRouter(prefix="/export", tags=["Export"])


@router.get("/pdf/{conversation_id}")
async def export_conversation_pdf(
    conversation_id: UUID,
    db: AsyncSession = Depends(get_database_session),
    current_user: dict = Depends(get_authenticated_user),
):
    """Export a conversation as a PDF file."""
    user_id = current_user.get("sub")

    # Fetch conversation messages
    result = await db.execute(
        select(ChatHistory)
        .where(
            ChatHistory.conversation_id == conversation_id,
            ChatHistory.user_id == user_id,
        )
        .order_by(ChatHistory.created_at)
    )
    messages = result.scalars().all()

    if not messages:
        raise HTTPException(status_code=404, detail="Conversation not found")

    # Generate PDF
    pdf_buffer = _generate_pdf(messages, conversation_id)

    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="KSP_Chat_{str(conversation_id)[:8]}.pdf"'
        },
    )


def _generate_pdf(messages: list, conversation_id: UUID) -> io.BytesIO:
    """Generate a PDF from conversation messages using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.lib.colors import HexColor
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    )

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=18,
        textColor=HexColor("#1e1b4b"),
        spaceAfter=12,
    )
    user_style = ParagraphStyle(
        "UserMsg",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#1f2937"),
        backColor=HexColor("#e0e7ff"),
        borderPadding=8,
        spaceAfter=8,
    )
    ai_style = ParagraphStyle(
        "AIMsg",
        parent=styles["Normal"],
        fontSize=10,
        textColor=HexColor("#1f2937"),
        spaceAfter=8,
    )
    sql_style = ParagraphStyle(
        "SQL",
        parent=styles["Code"],
        fontSize=8,
        textColor=HexColor("#4338ca"),
        backColor=HexColor("#f5f3ff"),
        borderPadding=6,
        spaceAfter=8,
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=8,
        textColor=HexColor("#6b7280"),
        spaceAfter=4,
    )

    elements = []

    # Header
    elements.append(Paragraph(
        "KSP Crime Intelligence Platform — Chat Export", title_style
    ))
    elements.append(Paragraph(
        f"Conversation ID: {str(conversation_id)[:8]}",
        meta_style,
    ))
    elements.append(Spacer(1, 10 * mm))

    # Messages
    for msg in messages:
        timestamp = str(msg.created_at)[:19]
        role_label = "👤 You" if msg.role == "user" else "🤖 AI Assistant"
        style = user_style if msg.role == "user" else ai_style

        elements.append(Paragraph(
            f"<b>{role_label}</b> — {timestamp}", meta_style
        ))

        # Truncate very long content for PDF
        content = msg.content[:2000]
        content = content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        elements.append(Paragraph(content, style))

        # SQL query if present
        if msg.sql_query:
            sql_text = msg.sql_query[:500]
            sql_text = sql_text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            elements.append(Paragraph(f"<b>SQL:</b> {sql_text}", sql_style))

        # Confidence
        if msg.confidence:
            elements.append(Paragraph(
                f"Confidence: {float(msg.confidence):.0%}", meta_style
            ))

        elements.append(Spacer(1, 5 * mm))

    # Footer
    elements.append(Spacer(1, 10 * mm))
    elements.append(Paragraph(
        "Generated by KSP Crime Intelligence Platform | Confidential",
        meta_style,
    ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
